version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=java
      - POSTGRES_USER=candidate
    ports:
      - "5432:5432"
    volumes:
      - ./src/sql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql